# Generated by Django 5.2.7 on 2026-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='種類'),
        ),
    ]
