# Generated by Django 5.2.7 on 2026-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_plant_description_alter_plant_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': '植物', 'verbose_name_plural': '植物一覧'},
        ),
    ]
