# Generated by Django 5.2.7 on 2026-02-26 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_plant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-performed_at'], 'verbose_name': '園芸作業', 'verbose_name_plural': '作業一覧'},
        ),
        migrations.AlterField(
            model_name='work',
            name='default_interval_days',
            field=models.PositiveIntegerField(default=0, verbose_name='作業間隔'),
        ),
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='作業内容'),
        ),
        migrations.AlterField(
            model_name='work',
            name='performed_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作業日'),
        ),
        migrations.AlterField(
            model_name='work',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='plant.plant', verbose_name='植物'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('pruning', '剪定'), ('fertilization', '施肥'), ('planting', '植付け')], max_length=20, verbose_name='作業名'),
        ),
    ]
