# Generated by Django 5.2.7 on 2026-04-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_work_options_alter_work_default_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='shooting_date',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='植物'),
        ),
    ]
