# Generated by Django 5.2.7 on 2026-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_plant_shooting_date_alter_work_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='shooting_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
