# Generated by Django 4.1.4 on 2022-12-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('text', models.TextField(verbose_name='内容')),
                ('category', models.ImageField(choices=[(1, 'バラ'), (2, '観葉植物'), (3, 'ラン'), (4, '果樹'), (5, '野菜'), (6, 'その他')], default=1, upload_to='', verbose_name='種類')),
                ('uetuke_date', models.DateField(default=django.utils.timezone.now, verbose_name='植付月日等')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '植物',
            },
        ),
    ]
