# Generated by Django 4.1.4 on 2022-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.IntegerField(choices=[(1, 'バラ'), (2, '観葉植物'), (3, 'ラン'), (4, '果樹'), (5, '野菜'), (6, 'その他')], default=1, verbose_name='種類'),
        ),
    ]
