# Generated by Django 4.1.4 on 2023-03-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_category_plant_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.category', verbose_name='カテゴリ'),
        ),
    ]
