# Generated by Django 4.1.4 on 2023-04-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='category',
            new_name='kinds',
        ),
    ]
