# Generated by Django 4.1.4 on 2023-04-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_rename_category_plant_kinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='kinds',
        ),
    ]
